-- Database Creation
CREATE DATABASE PIZZA;
USE PIZZA;

-- Creating Table order_details
CREATE TABLE ORDER_DETAILS (
	ORDER_DETAILS_ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    PIZZA_ID TEXT NOT NULL,
    QUANTITY INT NOT NULL,
    PRIMARY KEY(ORDER_DETAILS_ID),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

-- Creating Table orders
CREATE TABLE ORDERS (
    ORDER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_TIME TIME NOT NULL,
    PRIMARY KEY(ORDER_ID)
);

-- Creating Table pizza_types
CREATE TABLE PIZZA_TYPES (
	PIZZA_TYPE_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    CATEGORY TEXT NOT NULL,
    INGREDIENTS TEXT NOT NULL,
    PRIMARY KEY(PIZZA_TYPE_ID)
);

-- Creating Table pizzas
CREATE TABLE PIZZAS (
	PIZZA_ID INT NOT NULL,
    PIZZA_TYPE_ID INT NOT NULL,
    SIZE TEXT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PRIMARY KEY(PIZZA_ID),
    FOREIGN KEY(PIZZA_TYPE_ID) REFERENCES PIZZA_TYPES(PIZZA_TYPE_ID)
);